apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gvisor
spec:
  template:
    metadata:
      labels:
        workload-type: gvisor
        runtime: gvisor
    spec:
      taints:
      - key: gvisor
        value: "true"
        effect: NoSchedule
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["m"]
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values: ["6"]
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values: ["2xlarge"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gvisor
  limits:
    cpu: "16"
    memory: "64Gi"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30m
