apiVersion: v1
kind: Namespace
metadata:
  name: gvisor-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-gvisor-karpenter
  namespace: gvisor-test
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: gvisor-efs-test
  namespace: gvisor-test
spec:
  runtimeClassName: gvisor
  tolerations:
  - key: gvisor
    operator: Equal
    value: "true"
    effect: NoSchedule
  nodeSelector:
    runtime: gvisor
  containers:
  - name: test
    image: public.ecr.aws/amazonlinux/amazonlinux:2023
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: efs
      mountPath: /mnt/efs
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: "2Gi"
  volumes:
  - name: efs
    persistentVolumeClaim:
      claimName: efs-gvisor-karpenter
