apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3files-dynamic-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3files-dynamic-sc
  resources:
    requests:
      storage: 10Gi
