apiVersion: v1
kind: Pod
metadata:
  name: s3files-fio-gvisor
spec:
  runtimeClassName: gvisor
  nodeName: ip-172-31-9-46.us-west-2.compute.internal
  terminationGracePeriodSeconds: 5
  tolerations:
  - key: gvisor
    operator: Equal
    value: "true"
    effect: NoSchedule
  volumes:
  - name: s3files-vol
    persistentVolumeClaim:
      claimName: s3files-fio
  containers:
  - name: main
    image: ubuntu:22.04
    command:
    - /bin/bash
    - -c
    - |
      apt-get update -qq && apt-get install -y -qq fio jq >/dev/null 2>&1
      echo "READY"
      sleep infinity
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "4Gi"
    volumeMounts:
    - name: s3files-vol
      mountPath: /data
